# Generated by Django 3.2.5 on 2021-08-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=300)),
                ('imgpath', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=250)),
                ('status', models.IntegerField(default=0)),
                ('overallrating', models.IntegerField(default=3)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.service')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('adid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer')),
            ],
        ),
    ]
