# Generated by Django 3.2.5 on 2021-09-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_cid_service_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('workstatus', models.IntegerField(default=0)),
                ('cost', models.IntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('rating', models.IntegerField()),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.service')),
                ('technician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.technician')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.customer')),
            ],
        ),
    ]
