# Generated by Django 3.2.5 on 2021-09-12 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_service_imgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=650),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
