# Generated by Django 3.2.5 on 2021-09-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210912_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='overallrating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='technician',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.service'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.service'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.technician'),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
