# Generated by Django 3.2.5 on 2021-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210926_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='service',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='service',
            field=models.CharField(max_length=300),
        ),
    ]
