# Generated by Django 3.2.5 on 2021-09-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210926_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='users.customer'),
        ),
    ]
