# Generated by Django 3.2.5 on 2021-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_workrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='workstatus',
            field=models.CharField(max_length=200),
        ),
    ]
