# Generated by Django 3.2.5 on 2022-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('locations', models.CharField(max_length=300)),
            ],
        ),
    ]
