# Generated by Django 3.2.5 on 2022-09-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slotid', models.AutoField(primary_key=True, serialize=False)),
                ('slots', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('technician', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.technician')),
            ],
        ),
    ]
