# Generated by Django 3.2.5 on 2022-09-12 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_book_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrequest',
            name='datetime',
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workrequest',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='slot',
            field=models.CharField(default='10:00 to 11:00', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='slot',
            field=models.CharField(default='', max_length=200),
        ),
    ]
