# Generated by Django 3.2.5 on 2022-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220912_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrequest',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
